config/routes.rb
Rails.application.routes.draw do
  # Devise routes must be on top to get highest priority
  devise_for :admin_users, ActiveAdmin::Devise.config

  # When database is recreated, `rake db:schema:load` raises `ActiveAdmin::DatabaseHitDuringLoad`
  # https://github.com/activeadmin/activeadmin/issues/783#issuecomment-1199098069
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad

  namespace :haka do
    get "auth/sign_out", to: "/haka_auth#destroy"
    get 'auth/new', to: "/haka_auth#new"
    get "auth/consume", to: "/haka_auth#consume"
    post "auth/consume", to: "/haka_auth#consume"

    if Vaalit::Config.fake_auth_enabled?
      post "auth/fake_authentication", to: "/haka_auth#create_fake_authentication"
      get "auth/fake_authentication", to: "/haka_auth#new_fake_authentication"
    end
  end

  root :to => "public#index"

  get "/advocates", :to => "public#index", :as => :advocate_index

  namespace :advocates do
    get :index, :as => :advocates
    resources :alliances do
      resources :candidates do
        put :confirm_alliance, to: "candidates#confirm_alliance"
      end
    end

    resource :coalition, only: [:update]
  end

  namespace :registrations do
    root to: "/registrations#index"

    resource :candidate do
      post :cancel, to: "candidates#cancel"
    end
  end

  namespace :manage do
    get "configuration", :to => "configurations#index"
    resources :configuration, :only => [:index, :update, :edit] do
      put :disable_advocate_login, :to => "configurations#disable_advocate_login"
      put :enable_advocate_login,  :to => "configurations#enable_advocate_login"
    end

    resources :candidates, :only => [:index] do
      get :reduced, to: "candidates#reduced", on: :collection
    end

    resources :electoral_coalitions, :only => [:index]
    resources :electoral_alliances, :only => [:index]
    resource :danger_zone, :only => [:show] do
      post :give_candidate_numbers, to: "danger_zones#give_candidate_numbers"
    end
    resources :candidate_attribute_changes
  end
end

app/views/tools/index.html.erb
<h1>Vaaralliset toiminnot</h1>

<iframe width="420" height="345"
src="http://www.youtube.com/embed/V8rZWw9HE7o" frameborder="0"
allowfullscreen></iframe>

<h2>Ehdokasasettelu</h2>

<ul>
  <!-- # FIXME 6/2012
  <li>
    <#%= link_to 'Luo asiamiehille tunnukset', create_advocates_admin_electoral_alliances_path, :confirm => "Luodaanko asiamiesten tunnukset tietojen korjaamiseksi?\nSalasana välitetään jokaiselle asiamiehelle sähköpostitse." %>
    <ul>
      <li>Salasana välitetään jokaiselle sähköpostitse.</li>
      <li>Tunnus luodaan jokaisen liiton ensisijaiselle asiamiehelle.</li>
      <li>Liiton asiamies kohdistetaan käyttäjätunnukseen hetun perusteella.</li>
      <li>Jokaista hetua kohden luodaan vain yksi käyttäjätunnus.</li>
    </ul>
  </li> -->

  <li>
    <%= link_to 'Kirjoita ehdokkaille lähetettävä sähköposti', new_admin_email_path %>
    <ul>
      <li>Kirjoita viesti avautuvalta sivulta.</li>
      <li>Liitä kaikki eri kieliversiot samaan viestiin.</li>
      <li>Viestin voi lähettää kirjoittamisen jälkeen.</li>
    </ul>
  </li>
</ul>

<h3>Ehdokasnumerot</h3>

<ul>
  <li>
    <%= link_to 'Aseta vaalirenkaiden keskinäinen järjestys', admin_electoral_coalitions_path %> (Sivun oikeasta reunasta)
    <ul>
      <li>Liitä jokainen vaaliliitto vaalirenkaaseen.</li>
      <li>Luo myös jokaiselle itsenäiselle liitolle (ja ehdokkaalle) oma vaalirengas, jolla on sama nimi kuin liitolla.</li>
      <li>Määritä järjestys (peruste ehdokasnumeroille) sen jälkeen, kun KVL on arponut renkaiden ja itsenäisten liittojen keskinäisen järjestyksen.</li>
    </ul>
  </li>
  <li>
    <%= link_to 'Anna ehdokkaille numerot', give_numbers_admin_candidates_path, :confirm => "Jaetaanko ehdokasnumerot?" %>
    <ul>
      <li>Ks. ohjeet renkaiden järjestämisestä.</li>
      <li>Kun renkaiden keskinäinen järjestys on määritetty, ehdokasnumerot voidaan jakaa.</li>
      <li>Ehdokasnumerot jaetaan samassa järjestyksessä kuin missä ehdokkaat näkyvät "Ehdokkaat"-sivulla.</li>
    </ul>
  </li>
</ul>

<h3>Tarkastuslaskenta</h3>

<ul>
  <li>
    <%= link_to 'Merkitse tarkastuslaskenta valmiiksi!', ready_checking_minutes_path, :method => :post, :confirm => 'Onko jokaisen äänestysalueen tarkastuslaskenta valmis? Ääniä ei voi tämän jälkeen enää muokata.' %>
  </li>
</ul>