config/routes.rb
Rails.application.routes.draw do
  # Devise routes must be on top to get highest priority
  devise_for :admin_users, ActiveAdmin::Devise.config

  # When database is recreated, `rake db:schema:load` raises `ActiveAdmin::DatabaseHitDuringLoad`
  # https://github.com/activeadmin/activeadmin/issues/783#issuecomment-1199098069
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad

  namespace :haka do
    get "auth/sign_out", to: "/haka_auth#destroy"
    get 'auth/new', to: "/haka_auth#new"
    get "auth/consume", to: "/haka_auth#consume"
    post "auth/consume", to: "/haka_auth#consume"

    if Vaalit::Config.fake_auth_enabled?
      post "auth/fake_authentication", to: "/haka_auth#create_fake_authentication"
      get "auth/fake_authentication", to: "/haka_auth#new_fake_authentication"
    end
  end

  root :to => "public#index"

  get "/advocates", :to => "public#index", :as => :advocate_index

  namespace :advocates do
    get :index, :as => :advocates
    resources :alliances do
      resources :candidates do
        put :confirm_alliance, to: "candidates#confirm_alliance"
      end
    end

    resource :coalition, only: [:update]
  end

  namespace :registrations do
    root to: "/registrations#index"

    resource :candidate do
      post :cancel, to: "candidates#cancel"
    end
  end

  namespace :manage do
    get "configuration", :to => "configurations#index"
    resources :configuration, :only => [:index, :update, :edit] do
      put :disable_advocate_login, :to => "configurations#disable_advocate_login"
      put :enable_advocate_login,  :to => "configurations#enable_advocate_login"
    end

    resources :candidates, :only => [:index] do
      get :reduced, to: "candidates#reduced", on: :collection
    end

    resources :electoral_coalitions, :only => [:index]
    resources :electoral_alliances, :only => [:index]
    resource :danger_zone, :only => [:show] do
      post :give_candidate_numbers, to: "danger_zones#give_candidate_numbers"
    end
    resources :candidate_attribute_changes
  end
end

app/controllers/advocates/alliances_controller.rb
class Advocates::AlliancesController < AdvocatesController

  before_action :find_alliance, :only => [:show, :edit, :update]
  before_action :nav_paths, :only => [:index, :show]

  authorize_resource :electoral_alliance, :parent => false # Conf needed because ElectoralAlliance != Alliance. Without ":parent => false" authorization is not effective.

  def index
    @advocate_team = current_advocate_user&.advocate_team
    @team_alliances = @advocate_team&.electoral_coalition&.electoral_alliances&.by_numbering_order || []
    @alliances_without_coalition = current_advocate_user.electoral_alliances.by_numbering_order - @team_alliances
  end

  def new
    @alliance = current_advocate_user.electoral_alliances.build
  end

  def show
    if params[:isolatin]
      @encoding = "ISO-8859-1"
    else
      @encoding = "UTF-8"
    end

    respond_to do |format|
      format.html { }
      format.csv  { render :layout => false }
    end
  end

  def edit
  end

  def update
    if @alliance.update(alliance_params)
      flash[:notice] = "Muutokset tallennettu."
    else
      flash[:alert] = "Muutosten tallentaminen epäonnistui!"
      render :action => :edit and return
    end

    redirect_to advocates_alliance_path(@alliance)
  end

  def create
    @alliance = current_advocate_user.electoral_alliances.build(alliance_params)

    if @alliance.save
      flash[:notice] = "Vaaliliitto luotu!"
    else
      flash[:alert] = "Vaaliliiton luominen epäonnistui."
      render :action => :new and return
    end

    redirect_to advocates_alliance_path(@alliance)
  end

  protected

  # Return either
  # - alliance of mine (which is not linked to coalition yet)
  # - or alliance through AdvocateTeam (user A is viewing alliance of user B of the same team)
  def find_alliance
    @alliance = current_advocate_user.electoral_alliances.find_by(id: params[:id])

    if @alliance.nil? && current_advocate_user.advocate_team.present?
      @alliance = current_advocate_user.advocate_team.electoral_alliances.find(params[:id])
    end
  rescue ActiveRecord::RecordNotFound
    flash.alert = "Pyydettyä vaaliliittoa ei löytynyt tai sinulla ei ole oikeuksia siihen."
    redirect_to advocates_alliances_path
  end

  def nav_paths
    @_nav_paths = [{"Kaikki vaaliliitot" => advocates_alliances_path}]
  end

  def alliance_params
    params
      .require(:electoral_alliance)
      .permit(
        :name,
        :shorten,
        :expected_candidate_count,
        :invite_code
      )
  end
end

app/controllers/advocates/candidates_controller.rb
class Advocates::CandidatesController < AdvocatesController
  respond_to :html, :json, :only => :update

  before_action :find_alliance

  authorize_resource :electoral_alliance

  def new
    @candidate = Candidate.new
    @candidate.electoral_alliance = @alliance

    authorize! :create, @candidate
  end

  def index
    redirect_to advocates_alliance_url(@alliance)
  end

  def edit
    @candidate = @alliance.candidates.find(params[:id])

    authorize! :edit, @candidate
  end

  def show
    raise "Not implemented"
  end

  # Updates Candidate attributes (html form) and Candidate numbering order (xhr/json)
  def update
    @candidate = @alliance.candidates.find(params[:id])

    authorize! :update, @candidate

    if @candidate.log_and_update_attributes(candidate_params)
      flash[:notice] = "Muutokset tallennettu."
    else
      flash[:alert] = "Muutosten tallentaminen epäonnistui!"
      render :action => :edit and return
    end

    respond_with(@alliance) do |format|
      format.html { redirect_to advocates_alliance_path(@alliance) }
    end
  end

  def create
    @candidate = @alliance.candidates.build(candidate_params)

    authorize! :create, @candidate

    if @candidate.save
      flash[:notice] = "Ehdokas luotu!"
      redirect_to advocates_alliance_path(@alliance)
    else
      flash[:alert] = "Ehdokkaan luominen epäonnistui."
      render :action => :new
    end
  end

  def confirm_alliance
    candidate = @alliance.candidates.find(params[:candidate_id])

    if candidate.confirm_alliance!
      flash.notice = "Vaaliliitto vahvistettu!"
    else
      flash.error = "Vaaliliittoon vahvistaminen epäonnistui: #{candidate.errors.full_messages}"
    end

    redirect_to advocates_alliance_path(@alliance)
  end

  protected

  # Advocate can only edit Candidates which belong to Alliance they manage.
  # AdvocateTeam membership does not grant access to modify the Alliance or its Candidates.
  # Advocate can, however, view Candidates of belonging to any of the AdvocateTeam Alliances
  # in AlliancesController#show.
  def find_alliance
    @alliance = current_advocate_user
      .electoral_alliances
      .find(params[:alliance_id])
  rescue ActiveRecord::RecordNotFound
    flash.alert = "Pyydettyä kohdetta ei löytynyt tai sinulla ei ole oikeuksia pyydettyyn toimintoon. Vaaliliiton edustaja voi muokata vain oman vaaliliittonsa ehdokastietoja."
    redirect_to advocates_alliance_path(params[:alliance_id]) and return
  end

  def candidate_params
    params
      .require(:candidate)
      .permit(
        :lastname,
        :firstname,
        :student_number,
        :faculty_id,
        :address,
        :postal_code,
        :postal_city,
        :phone_number,
        :email,
        :candidate_name,
        :notes,
        :numbering_order_position
      )
  end
end

app/controllers/advocates/coalitions_controller.rb
class Advocates::CoalitionsController < AdvocatesController
  before_action :set_advocate_team
  before_action :set_coalition

  def update
    authorize! :update, ElectoralCoalition, electoral_coalition_id: @coalition&.id
    if @advocate_team.nil?
      flash.alert = "Tarvitset ensin edustajatiimin voidaksesi liittää vaaliliiton vaalirenkaaseen."
      redirect_to advocates_alliances_path and return
    end

    if @coalition.nil?
      flash.alert = "Pyydettyä vaalirengasta ei löydy."
      redirect_to advocates_alliances_path and return
    end

    alliance = current_advocate_user.electoral_alliances.find(params[:electoral_alliance_id])

    if @coalition.electoral_alliances << alliance
      flash.notice = <<-MSG
        Vaaliliitto "#{alliance.shorten}" kytkettiin renkaaseen "#{@coalition.shorten}".
      MSG
    else
      flash.alert = "Vaaliliiton kytkeminen vaalirenkaaseen epäonnistui"
    end

    redirect_to advocates_alliances_path
  rescue ActiveRecord::RecordNotFound
    flash.alert = "Odottamaton virhe, pyydettyä tietoa ei löytynyt tai pääsy kielletty."
    redirect_to advocates_alliances_path
  end

  protected

  def set_advocate_team
    @advocate_team = current_advocate_user&.advocate_team
  end

  def set_coalition
    @coalition = current_advocate_user&.advocate_team&.electoral_coalition
  end
end

app/controllers/advocates_controller.rb
class AdvocatesController < ApplicationController
  before_action :require_advocate_user
  before_action :authorize_this!

  def index
  end

  protected

  def authorize_this!
    authorize! :access, :advocate
  end

  def require_advocate_user
    unless current_advocate_user.present?
      flash.alert = <<-MSG.squish
        Käyttäjätunnuksellasi ei ole vaaliliiton edustajan oikeuksia.
        Tarvittaessa pyydä oikeudet HYYn vaalityöntekijältä.
      MSG

      redirect_to registrations_root_path and return
    end
  end
end

app/views/advocates/alliances/_alliance_table.html.erb
  <table>
    <thead>
      <th>Vaaliliitto</th>
      <th>Edustaja</th>
      <th>Vaalirengas</th>
      <th>Ehdokkaita</th>
      <th>Uusia</th>
      <th>Tavoite</th>
      <th>Huomioita</th>
      <th><i class="icon-share"></i> CSV</th>
      <th><i class="icon-share"></i> CSV</th>
    </thead>

    <tbody>
      <% alliances.each do |a| %>
        <tr>
          <td><%= link_to a.shorten, advocates_alliance_path(a) %></td>
          <td>
            <% if a&.advocate_user == current_advocate_user %>
              <%# &#x1F464; silhouette of person %>
              <span title="Minä itse!">&#x1F464;</span>
            <% end %>
            <%= a&.advocate_user&.friendly_name %>
          </td>
          <td>
            <% if a.electoral_coalition.present? %>
              <%= a.electoral_coalition.shorten %>
            <% elsif current_advocate_user&.advocate_team&.electoral_coalition.present? %>
              <%= button_to "Liitä renkaaseen",
                advocates_coalition_path(electoral_alliance_id: a.id),
                method: :put,
                class: "btn btn-info",
                data: {
                  confirm: <<-MSG.squish
                    Liitetäänkö vaaliliitto "#{a.shorten}"
                    renkaaseen "#{current_advocate_user.advocate_team.electoral_coalition.shorten}"?
                  MSG
                }
              %>
            <% end %>
          </td>
          <td><%= a.accepted_candidates.count %></td>
          <td><%= a.incoming_candidates.count %></td>
          <td><%= a.expected_candidate_count %></td>
          <td>
            <% if alliance_ready?(a) %>
              <span class='alliance-ready'>OK</span>
            <% else %>
              <% if a.accepted_candidates.count != a.expected_candidate_count %>
                Tarkista ehdokasmäärä.
              <% end %>

              <% if a.electoral_coalition.nil? %>
                Ei vaalirengasta.
              <% end %>
            <% end %>
          </td>
          <td><%= link_to "ISO-Latin", advocates_alliance_path(a, :format => :csv, :isolatin => true) %></td>
          <td><%= link_to "UTF-8", advocates_alliance_path(a, :format => :csv) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/advocates/alliances/_form.html.erb
<h2>Vaaliliiton ensisijainen edustaja</h2>
  <%= current_advocate_user.friendly_name %> (<%= current_advocate_user.email %>)

<h2>Vaaliliitto</h2>

<%= f.input :name,
  :label => "Vaaliliiton nimi"
%>

<%= f.input :shorten,
  :label => "Vaaliliiton lyhenne (2-6 merkkiä)",
  :hint => "Suosituksena on valita sama lyhenne kuin aiemmissa vaaleissa.
    Lyhennettä käytetään vaalituloksen esittämisessä: esimerkiksi TaVi, ParasS, WTF.
    HYY pidättää oikeuden muuttaa lyhennettä tarvittaessa."
%>

<%= f.input :expected_candidate_count,
  label: "Ehdokkaiden odotettu lukumäärä",
  hint:
    "Jätä kenttä tyhjäksi, jos ehdokkaiden odotettu lukumäärä ei ole vielä tiedossa.
    Ehdokkaiden odotettu lukumäärä on syötettävä ennen ehdokasasettelun päättymistä.
    Tietoa käytetään varmistamaan, että kaikki ehdokastiedot on ilmoitettu."
%>

<%= f.input :invite_code,
  label: "Kutsukoodi vaaliliittoon ilmoittautumiseksi",
  hint: "Kutsukoodi suojaa vaaliliittoa tuntemattomilta ehdokkailta.
    Ehdokkaaksi ilmoittautuvan henkilön on tunnettava kutsukoodi
    voidakseen ilmoittautua vaaliliiton ehdokkaaksi.
    <br><br>
    Kutsukoodin voi vaihtaa milloin tahansa.
    Kutsukoodin tulee olla voimassa sillä hetkellä, kun ehdokas saapuu ilmoittautumaan.
    Kutsukoodin vaihtaminen ei vaikuta aiemmin vastaanotettuihin ilmoittautumisiin.
    <br><br>
    Voit käyttää järjestelmän arpomaa satunnaiskoodia tai valita oman helpommin muistettavan
    merkkijonon. Kirjaimet, numerot ja tavuviiva ovat sallittuja.".html_safe
 %>

app/views/advocates/alliances/edit.html.erb
<p>
  &larr; <%= link_to "Palaa tallentamatta", advocates_alliance_path(@alliance) %>
</p>

<%= semantic_form_for @alliance, :url => advocates_alliance_path(@alliance) do |f| %>

  <%= render :partial => "form", :locals => { :alliance => @alliance, :f => f } %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :button, :label => "Tallenna" %>
  <% end %>
<% end %>

app/views/advocates/alliances/index.html.erb
<h1>Vaalirengas</h1>

<p>
  Edustajatiimi jakaa näkyvyyden vaalirenkaan vaaliliittojen ehdokkaisiin.
  Vain vaaliliiton oma edustaja voi muokata ehdokastietoja.
</p>

<% if @advocate_team.present? %>
  <dl>
    <dt>Edustajatiimi</dt>
    <dd><%= @advocate_team.name %></dd>

    <dt>Tiimin jäsenet</dt>
    <dd>
      <%= @advocate_team.advocate_users.map(&:friendly_name).join(", ") %>
    </dd>
  </dl>

  <% if @advocate_team.electoral_coalition.present? %>
    <h2><%= @advocate_team.electoral_coalition.name %></h2>
  <% else %>
    <p>
      &raquo; Muodosta edustajatiimille vaalirengas kirjoittamalla sähköpostiviesti vaalit@hyy.fi.
    </p>
  <% end %>
<% else %>
  <p>
    Edustajatiimin muodostamiseksi ilmoita sähköpostitse HYYn vaaliorganisaatiolle seuraavat tiedot:
    <ul>
      <li>
        Edustajatiimin nimi (voi olla sama kuin vaalirenkaan nimi)
      </li>
      <li>
        Edustajatiimin jäsenten nimi, sähköpostiosoite ja opiskelijanumero.
        Jos vaaliliiton edustajalla on jo edustajatunnus, riittää ilmoittaa pelkkä nimi.
      </li>
    </ul>
  </p>
<% end %>

<% if @team_alliances.any? %>
  <%= render partial: "alliance_table", locals: { alliances: @team_alliances } %>
<% end %>

<% if @alliances_without_coalition.any? %>
  <h2>Vaaliliitot ilman vaalirengasta</h2>

  <%= render partial: "alliance_table", locals: { alliances: @alliances_without_coalition } %>
<% end %>

<% if can? :create, ElectoralAlliance %>
  <p>
    &raquo; <%= link_to "Luo uusi vaaliliitto", new_advocates_alliance_path %>
  </p>
<% end %>

<h3>Ehdokasasettelu päättyy <%= friendly_datetime(GlobalConfiguration.candidate_nomination_ends_at) %></h3>
  <ul>
    <li>
      Edustaja vastaa siitä, että vaaliliiton kaikki ehdokkaat ovat järjestelmässä ehdokasasettelun
      päättymiseen mennessä.
    </li>
    <li>
      Ehdokasasettelun päättymisen jälkeen tietoihin voi tehdä korjauksia ehdokasilmoituksen
      perumisen määräaikaan saakka.
    </li>
    <li>
      Ehdokastietojen korjausten, järjestyksen ja peruutusten määräaika:
      <%= friendly_datetime(GlobalConfiguration.candidate_data_is_freezed_at) %>
    </li>
  </ul>
</p>

<hr>

<h3>Ehdokasnumeroinnista:</h3>
  <ul>
    <li>
      Ehdokasnumerot määräytyvät vaaliliiton sisällä ehdokkaiden järjestyksen mukaan.
    </li>

    <li>
      Ehdokkaiden järjestys on <strong>aina</strong> vaaliliiton edustajan vastuulla.
      <br>
      Uudet ehdokasilmoittautumiset eivät asetu valmiiksi esimerkiksi aakkosjärjestykseen,
      <br>
      koska ei ole takeita, onko aakkosjärjestys vaaliliiton ehdokkaiden toivottu järjestys.
    </li>


    <li>
      Tarkista ehdokkaiden järjestys ehdokasasettelun päättymisen jälkeen ennen
      korjausten määräaikaa
      <%= friendly_datetime(GlobalConfiguration.candidate_data_is_freezed_at) %>.
    </li>

    <li>
      Perutut ehdokasilmoittautumiset eivät vaikuta ehdokasnumerointiin.
    </li>
  </ul>

<h3>Vaalirenkaista:</h3>
  <ul>
    <li>
      Vaalirenkaan edustajan on ilmoitettava vaaliliittojen haluttu järjestys
      sähköpostilla vaalit@hyy.fi.
    </li>

    <li>
      Ehdokasnumerot määräytyvät vaalirenkaan sisällä vaaliliittojen järjestyksen mukaan.
    </li>

    <li>
      Keskusvaalilautakunta arpoo vaalirenkaiden keskinäisen järjestyksen, kun ehdokasnumeot jaetaan.
    </li>
  </ul>

<h3>CSV-tiedoston tuominen Exceliin (ISO-Latin):</h3>
  <ol>
    <li>Avaa CSV-tiedosto Exceliin.</li>
    <li>Valitse ja mustaa koko sarake 'A'.</li>
    <li>Valitse: Tiedot > Teksti sarakkeisiin</li>
    <li>Valitse: Tiedostolaji: Erotettu > Seuraava.</li>
    <li>Valitse: Erottimet: Pilkku > Valmis.</li>
  </ol>

<p>
  Jos CSV-tiedoston ääkköset näkyvät väärin ISO-Latin-merkistökoodauksella,
  kokeile UTF-8-versiota.
</p>

app/views/advocates/alliances/new.html.erb
<p>
  &larr; <%= link_to "Palaa tallentamatta".html_safe, advocates_alliances_path %>
</p>


<%= semantic_form_for @alliance, :url => advocates_alliances_path(@alliance) do |f| %>

  <%= render :partial => "form", :locals => { :alliance => @alliance, :f => f } %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :button, :label => "Tallenna" %>
  <% end %>
<% end %>

app/views/advocates/alliances/show.csv.erb
<% if @alliance.candidates.any? -%>
<%= @alliance.to_csv(@encoding).html_safe -%>
<% else %>
Vaaliliitossa ei ole ehdokkaita.
<% end %>

app/views/advocates/alliances/show.html.erb
<% @_nav_paths << {@alliance.name => false} %>


<h1>[<%= @alliance.shorten %>] <%= @alliance.name %></h1>

<ul>
  <li>
    Kutsukoodi: <strong><%= @alliance.invite_code %></strong>
  </li>

  <li>
    Ehdokkaita hyväksytty:
    <%= @alliance.accepted_candidates.count %>
    /
    <%= @alliance.expected_candidate_count ? @alliance.expected_candidate_count : '-' %>
  </li>

  <li>
    Ehdokkaita hyväksyttävänä: <%= @alliance.incoming_candidates.count %>
  </li>

  <% if can? :update, ElectoralAlliance %>
    <li><%= link_to "Muokkaa vaaliliiton tietoja", edit_advocates_alliance_path(@alliance) %></li>
  <% else %>
    <li>Ehdokasasettelu on päättynyt eikä vaaliliittoa voi muokata.</li>
  <% end %>
</ul>

<h2>Ohjeita</h2>
<ul>
  <li>
    Vaaliliiton edustajan on hyväksyttävä jokainen ehdokas vaaliliittoon.
    Tällä estetään epätoivotun ehdokkaan pääsy vaaliliittoon huomaamatta.
  </li>
  <li>
    Hyödynnä selaimen zoom-toimintoa (ctrl+ tai cmd+), jos teksti on liian pientä.
  </li>
  <li>
    Ehdokasnumerot jaetaan nousevassa järjestyksessä:
    <br/>
    listan ensimmäinen ehdokas saa pienimmän ehdokasnumeron ja listan viimeinen ehdokas suurimman.
  </li>
</ul>

<% if @alliance.candidates.any? %>
  <%= render partial: "advocates/candidates/list",
    locals: {
      alliance: @alliance,
      scope: "advocates"
    }
  %>
<% else %>
  <p>
    Vaaliliitossa ei ole yhtään ehdokasta.
  </p>
<% end %>